#!/bin/bash
iptables -P INPUT DROP   # politica por defecto: descartar
iptables -P FORWARD DROP # politica por defecto: descartar
iptables -P OUTPUT DROP  # politica por defecto: descartar
#CONEXION A INTERNET
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT
#CONEXIONES HACIA EL SERVIDOR 
iptables -A INPUT -p tcp -d 192.168.1.13 -dport 80 -j ACCEPT
iptables -A INPUT -p tcp -d 192.168.1.13 -dport 9088 -j ACCEPT
iptables -A INPUT -p tcp -d 192.168.1.13 -dport 22 -j ACCEPT
iptables -A INPUT -p tcp -d 192.168.1.13 -dport 443 -j ACCEPT
#CONEXIONES DESDE EL SERVIDOR 
iptables -A OUTPUT -p tcp -d 192.168.1.13 -dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -d 192.168.1.13 -dport 9088 -j ACCEPT
iptables -A OUTPUT -p tcp -d 192.168.1.13 -dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp -d 192.168.1.13 -dport 443 -j ACCEPT
#Verificación:
iptables -L -n